# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/samsung/gte-common/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/samsung/gte-common

PRODUCT_COPY_FILES += \
    vendor/samsung/gte-common/proprietary/lib/libaudiosa.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libaudiosa.so \
    vendor/samsung/gte-common/proprietary/lib/libmysound.so:$(TARGET_COPY_OUT_SYSTEM)/lib/libmysound.so \
    vendor/samsung/gte-common/proprietary/lib/soundfx/libaudioeffectoffload.so:$(TARGET_COPY_OUT_SYSTEM)/lib/soundfx/libaudioeffectoffload.so \
    vendor/samsung/gte-common/proprietary/lib/soundfx/libmyspace.so:$(TARGET_COPY_OUT_SYSTEM)/lib/soundfx/libmyspace.so
